//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.necsws.healthcareportal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Service_ID { get; set; }
        public int Doctor_ID { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Date { get; set; }
        public string Symptoms { get; set; }
        public string Appointment_Status { get; set; }
        public System.DateTime Created_At { get; set; }
        public Nullable<System.DateTime> Modified_At { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Service Service { get; set; }
    }
}
