//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training.healthcareportal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Qualification
    {
        public int ID { get; set; }
        public int Qualification_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
