//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training.healthcareportal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Doctor_Qualification = new HashSet<Doctor_Qualification>();
            this.Doctor_Services = new HashSet<Doctor_Services>();
            this.PatientDoctorDetails = new HashSet<PatientDoctorDetail>();
        }
    
        public int DoctorID { get; set; }
        public int IMA_No { get; set; }
        public string FullName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public int YearsOfExperience { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Doctor_Qualification> Doctor_Qualification { get; set; }
        public virtual ICollection<Doctor_Services> Doctor_Services { get; set; }
        public virtual ICollection<PatientDoctorDetail> PatientDoctorDetails { get; set; }
    }
}
