//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.necsws.healthcareportal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeOfPayment
    {
        public ModeOfPayment()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int PaymentModeID { get; set; }
        public string PaymentModeName { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
