//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training.healthcareportal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.PatientDoctorDetails = new HashSet<PatientDoctorDetail>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int PatientID { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public double Weight { get; set; }
        public double Height { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string HealthInsuranceID { get; set; }
        public string EmergencyContactPersonDetails { get; set; }
        public System.DateTime Created_At { get; set; }
        public Nullable<System.DateTime> Modified_At { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<PatientDoctorDetail> PatientDoctorDetails { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
