//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training.healthcareportal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Doctor_Services = new HashSet<Doctor_Services>();
        }
    
        public int Service_ID { get; set; }
        public string Service_Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Doctor_Services> Doctor_Services { get; set; }
    }
}
